import os
import pathlib

HERE = pathlib.Path("__file__")
BACKEND_DIR = HERE.parent.parent.absolute()

STACK_NAME_DEV = "vis-assis-backend-dev"
STACK_NAME_PROD = "vis-assis-backend-prod"

STACK_NAME = STACK_NAME_DEV

# CDK outputs export names
CDK_OUT_KEY_S3_BUCKET_SAGEMAKER_INPUT_NAME = "SagemakerInputS3BucketName"
CDK_OUT_EXPORT_S3_BUCKET_SAGEMAKER_INPUT_NAME = (
    f"{STACK_NAME}-{CDK_OUT_KEY_S3_BUCKET_SAGEMAKER_INPUT_NAME}"
)

CDK_OUT_KEY_S3_BUCKET_SAGEMAKER_OUTPUT_NAME = "SagemakerOutputS3BucketName"
CDK_OUT_EXPORT_S3_BUCKET_SAGEMAKER_OUTPUT_NAME = (
    f"{STACK_NAME}-{CDK_OUT_KEY_S3_BUCKET_SAGEMAKER_OUTPUT_NAME}"
)

CDK_OUT_KEY_S3_BUCKET_PRODUCTION_MODELS_NAME = "ModelArtifactsProductionS3BucketName"
CDK_OUT_EXPORT_S3_BUCKET_PRODUCTION_MODELS_NAME = (
    f"{STACK_NAME}-{CDK_OUT_KEY_S3_BUCKET_PRODUCTION_MODELS_NAME}"
)

CDK_OUT_KEY_S3_BUCKET_INPUT_IMAGES_NAME = "InputImagesS3BucketName"
CDK_OUT_EXPORT_S3_BUCKET_INPUT_IMAGES_NAME = (
    f"{STACK_NAME}-{CDK_OUT_KEY_S3_BUCKET_INPUT_IMAGES_NAME}"
)

CDK_OUT_KEY_USER_SAGEMAKER_TEAM = "SagemakerDataScientistTeam"
CDK_OUT_EXPORT_USER_SAGEMAKER_TEAM = f"{STACK_NAME}-{CDK_OUT_KEY_USER_SAGEMAKER_TEAM}"

CDK_OUT_KEY_SAGEMAKER_DOMAIN_ID = "SagemakerDomainID"
CDK_OUT_EXPORT_SAGEMAKER_DOMAIN_ID = f"{STACK_NAME}-{CDK_OUT_KEY_SAGEMAKER_DOMAIN_ID}"

CDK_OUT_KEY_SAGEMAKER_DOMAIN_ARN = "SagemakerDomainARN"
CDK_OUT_EXPORT_SAGEMAKER_DOMAIN_ARN = f"{STACK_NAME}-{CDK_OUT_KEY_SAGEMAKER_DOMAIN_ARN}"

CDK_OUT_KEY_COGNITO_USER_POOL_ID = "CognitoUserPoolId"
CDK_OUT_EXPORT_COGNITO_USER_POOL_ID = f"{STACK_NAME}-{CDK_OUT_KEY_COGNITO_USER_POOL_ID}"

CDK_OUT_KEY_COGNITO_USER_POOL_CLIENT_ID = "CognitoUserPoolClientId"
CDK_OUT_EXPORT_COGNITO_USER_POOL_CLIENT_ID = (
    f"{STACK_NAME}-{CDK_OUT_KEY_COGNITO_USER_POOL_CLIENT_ID}"
)

CDK_OUT_KEY_COGNITO_IDENTITY_POOL_ID = "CognitoIdentityPoolId"
CDK_OUT_EXPORT_COGNITO_IDENTITY_POOL_ID = (
    f"{STACK_NAME}-{CDK_OUT_KEY_COGNITO_IDENTITY_POOL_ID}"
)

CDK_OUT_KEY_API_GATEWAY_ENDPOINT = "ApiGatewayEndpoint"
CDK_OUT_EXPORT_API_GATEWAY_ENDPOINT = f"{STACK_NAME}-{CDK_OUT_KEY_API_GATEWAY_ENDPOINT}"

CDK_OUT_KEY_SAGEMAKER_DEPTH_MODEL_PACKAGE_GROUP_NAME = (
    "vis-assis-depth-model-package-group"
)
CDK_OUT_EXPORT_SAGEMAKER_DEPTH_MODEL_PACKAGE_GROUP_NAME = (
    f"{STACK_NAME}-{CDK_OUT_KEY_SAGEMAKER_DEPTH_MODEL_PACKAGE_GROUP_NAME}"
)

CDK_OUT_KEY_SAGEMAKER_TTS_MODEL_PACKAGE_GROUP_NAME = "vis-assis-tts-model-package-group"
CDK_OUT_EXPORT_SAGEMAKER_TTS_MODEL_PACKAGE_GROUP_NAME = (
    f"{STACK_NAME}-{CDK_OUT_KEY_SAGEMAKER_TTS_MODEL_PACKAGE_GROUP_NAME}"
)

CDK_OUT_KEY_SAGEMAKER_VOCODER_MODEL_PACKAGE_GROUP_NAME = (
    "vis-assis-vocoder-model-package-group"
)
CDK_OUT_EXPORT_SAGEMAKER_VOCODER_MODEL_PACKAGE_GROUP_NAME = (
    f"{STACK_NAME}-{CDK_OUT_KEY_SAGEMAKER_VOCODER_MODEL_PACKAGE_GROUP_NAME}"
)

CDK_OUT_KEY_SAGEMAKER_IMAGE_CAPTIONING_MODEL_PACKAGE_GROUP_NAME = (
    "vis-assis-image-captioning-model-package-group"
)
CDK_OUT_EXPORT_SAGEMAKER_IMAGE_CAPTIONING_MODEL_PACKAGE_GROUP_NAME = (
    f"{STACK_NAME}-{CDK_OUT_KEY_SAGEMAKER_IMAGE_CAPTIONING_MODEL_PACKAGE_GROUP_NAME}"
)

CDK_OUT_KEY_SAGEMAKER_OBJECT_DETECTION_MODEL_PACKAGE_GROUP_NAME = (
    "vis-assis-detection-model-package-group"
)
CDK_OUT_EXPORT_SAGEMAKER_OBJECT_DETECTION_MODEL_PACKAGE_GROUP_NAME = (
    f"{STACK_NAME}-{CDK_OUT_KEY_SAGEMAKER_OBJECT_DETECTION_MODEL_PACKAGE_GROUP_NAME}"
)

CDK_OUT_KEY_SAGEMAKER_NAVIGATION_MODEL_PACKAGE_GROUP_NAME = (
    "vis-assis-navigation-model-package-group"
)
CDK_OUT_EXPORT_SAGEMAKER_NAVIGATION_MODEL_PACKAGE_GROUP_NAME = (
    f"{STACK_NAME}-{CDK_OUT_KEY_SAGEMAKER_NAVIGATION_MODEL_PACKAGE_GROUP_NAME}"
)

CDK_OUT_KEY_SAGEMAKER_EXECUTION_ROLE_ARN = "SagemakerExecutionRoleARN"
CDK_OUT_EXPORT_SAGEMAKER_EXECUTION_ROLE_ARN = (
    f"{STACK_NAME}-{CDK_OUT_KEY_SAGEMAKER_EXECUTION_ROLE_ARN}"
)

CDK_OUT_KEY_SAGEMAKER_PIPELINE_LAMBDA_ROLE_ARN = "SagemakerPipelineLambdaRoleARN"
CDK_OUT_EXPORT_SAGEMAKER_PIPELINE_LAMBDA_ROLE_ARN = (
    f"{STACK_NAME}-{CDK_OUT_KEY_SAGEMAKER_PIPELINE_LAMBDA_ROLE_ARN}"
)

CDK_OUT_KEY_EVENTBRIDGE_PIPELINE_EXECUTION_ROLE_ARN = (
    "EventBridgeSagemakerPipelineExecutionRoleARN"
)
CDK_OUT_EXPORT_EVENTBRIDGE_PIPELINE_EXECUTION_ROLE_ARN = (
    f"{STACK_NAME}-{CDK_OUT_KEY_EVENTBRIDGE_PIPELINE_EXECUTION_ROLE_ARN}"
)

CDK_OUT_KEY_DEFAULT_HF_TOKEN_SECRET_NAME = (
    "DefaultHFTokenSecretName"
)
CDK_OUT_EXPORT_DEFAULT_HF_TOKEN_SECRET_NAME = (
    f"{STACK_NAME}-{CDK_OUT_KEY_DEFAULT_HF_TOKEN_SECRET_NAME}"
)

CDK_OUT_KEY_REGION = os.environ.get('AWS_REGION')
AVAILABILITY_ZONES = [f"{CDK_OUT_KEY_REGION}a", f"{CDK_OUT_KEY_REGION}c"]
CDK_OUT_EXPORT_REGION = f"{STACK_NAME}-{CDK_OUT_KEY_REGION}"

# Boto3 created resources
BOTO3_DEPTH_PIPELINE_NAME = f"{STACK_NAME}-depth-pipeline"
BOTO3_IMAGE_CAPTIONING_PIPELINE_NAME = f"{STACK_NAME}-image-captioning-pipeline"
BOTO3_OBJECT_DETECTION_PIPELINE_NAME = f"{STACK_NAME}-object-detection-pipeline"
BOTO3_TTS_PIPELINE_NAME = f"{STACK_NAME}-tts-pipeline"
BOTO3_VOCODER_PIPELINE_NAME = f"{STACK_NAME}-vocoder-pipeline"
BOTO3_NAVIGATION_PREPARATION_PIPELINE_NAME = f"{STACK_NAME}-navigation-training-pipeline"
BOTO3_NAVIGATION_DEPLOYMENT_PIPELINE_NAME = f"{STACK_NAME}-navigation-deployment-pipeline"
